epochs: 7
batch: 1024
lr: 0.001
data_ratio: 0.01
early_stop:
  criteria: 1e-7
  patience: 5
physics:
  toggled: True
  colloc_data_ratio: 0.1
  delayed_start: 0
val_split: 0.1
loss_balancing:
  type: fixed
  params:
    alpha_data: 1.0
    alpha_physics: 1.0