lr: 0.001
epochs: 2500
batch: 8096
early_stop: 
  criteria: 1e-7
  patience: 200
loss_balancing:
  type: softadapt
  params:
    loss_weighted: False
    beta: 0.3
    epsilon: 1e-8
    bd_order: 5

data_ratio: 1.0
val_split: 0.1
physics:
  toggled: True
  colloc_data_ratio: 5.0
  delayed_start: 0