batch: 252
data_ratio: 0.01
early_stop:
  criteria: 1e-7
  patience: 200
epochs: 2500
loss_balancing:
  params:
    bd_order: 5
    beta: 0.3
    epsilon: 1e-8
    loss_weighted: false
  type: softadapt
lr: 0.001
physics:
  colloc_data_ratio: 0.5
  delayed_start: 0
  toggled: true
val_split: 0.1
